### ISSUE TITLE
Add Icon into plugin

### ISSUE THREAD

**Issue by dugite-code** [TB-throwback/LookOut-fix-version#20]
Icon currently isn't shown in the plugin and needs to be inserted

**Comment by ovari** [comment]
Do you have an icon?

[Transport Neutral Encapsulation Format (TNEF)](https://en.wikipedia.org/wiki/Transport_Neutral_Encapsulation_Format)

Transport Neutral Encapsulation Format (TNEF) icon
![Transport Neutral Encapsulation Format (TNEF) icon](https://user-images.githubusercontent.com/17465872/49008143-3e3d7f80-f1c1-11e8-99a9-30aa44d158df.png)

LookOut icon (alpha)
![LookOut icon (alpha)](https://user-images.githubusercontent.com/17465872/49008257-7c3aa380-f1c1-11e8-8d9b-4ab89aca8d3b.png)

What do you think of a LookOut icon with the bird removed so that just an envelope and the Transport Neutral Encapsulation Format (TNEF) icon?

LookOut icon (beta)
![LookOut icon (beta)](https://user-images.githubusercontent.com/17465872/49008910-2d8e0900-f1c3-11e8-953f-d96090bb88c1.png)

Hope this helps.

All the best.

**Comment by dugite-code** [comment]
@ovari I do currently have an Icon. Although I do accept it's rather generic and might benefit from some work. The main thing is I need to get around to implementing it.

<img src="https://raw.githubusercontent.com/dugite-code/LookOut-fix-version/c2002bf683707db912340384ef4b75b8da595c59/icon.svg?sanitize=true" width="80" align="top">

**Comment by ovari** [comment]
Don't know if TNEF has an official logo. We created the logo by rotating the 1/4 of the logo 3 times and then making each 1/4 a different colour. Then the image was placed in an image of an open envelop. The colour of the envelop was set to the colour of the creases in the envelop in the Thunderbird icon. Should be okay to use the image as we composed it.

**Comment by ovari** [comment]
Done at https://github.com/dugite-code/LookOut-fix-version/pull/22

Please accept pull request to merge.

Thank you

**Comment by ovari** [comment]
![loicon-64](https://user-images.githubusercontent.com/17465872/49056001-dda85400-f24d-11e8-8e78-3bb29afa533f.png)

1. Need to update icon in README.MD at:
https://github.com/dugite-code/LookOut-fix-version

2. Need to update icon at ATN:
https://addons.thunderbird.net/addon/lookout-fix-version/
