### ISSUE TITLE
Preference dialogue not accessible

### ISSUE THREAD

**Issue by dugite-code** [TB-throwback/LookOut-fix-version#86]
The existing options.xhtml isn't accessible from the add-ons Manager list

**Comment by jobisoft** [comment]
It is caused by the session_restore API, which delays registering the options page and somehow it is too late. I added the session_restore API to delay add-on start because we had issues when it was started too early.

I just tested in TB99, where the session API is not needed anymore (because all add-ons have a delayed background startup). And there it works. Will test some more.

Are you on Daily? The change is not yet on Beta, but hopefully with 98.b03 next week. So you could test on Beta as well than.
