### ISSUE TITLE
Attempting to get working on TB 114 Beta

### ISSUE THREAD

**Issue by logan-dunbar** [TB-throwback/LookOut-fix-version#98]
- I am running the latest version - Yes
- I checked the documentation and found no answer - Yes
- I checked to make sure that this issue has not already been filed - Yes
- I have read the FAQ - Yes

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu 22.04.1
* Thunderbird version number: 114.0b1
* 64 bit/32 bit: 64
* LookOut (fix version) version number: master branch (with typo fixed)

## Current Behavior

After fixing typo in my [pull request](https://github.com/TB-throwback/LookOut-fix-version/pull/97), it gets stuck in startup loop:

>LookOut: Entering LookoutLoad()
>LookOut:    initialisation incomplete after 10 trials. I give up!

It looks like `messageHeaderSink` is never not `undefined`.

## Steps to Reproduce

Install master version with typo fixed, reload extension, see logs in debugger.

I'm new to extension development, I'm not sure why `messageHeaderSink` is not loading or where to fix it, so any help would be appreciated!

**Comment by dugite-code** [comment]
Good catch on that 5 year old typo. I'm surprised it's never come up before.

We are replacing the in-build Thunderbird messageHeaderSink in the lookout startup function [L629](https://github.com/TB-throwback/LookOut-fix-version/blob/master/src/chrome/content/lookout.js#L629). This is very much a legacy method as Lookout is utilizing the Legacy add-on [wrapper-apis](https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis). What needs to be done is to transition to a full mailExtension

The mailExtension API docs can be found [here](https://webextension-api.thunderbird.net/en/latest/). Last time I worked through it I couldn't find a way to fetch Thunderbirds internal messageID, you could only access the [message header ID](https://webextension-api.thunderbird.net/en/latest/messageDisplay.html#getdisplayedmessage-tabid), in order to access the [messageattachment](https://webextension-api.thunderbird.net/en/latest/messages.html#messageattachment)

**Comment by dugite-code** [comment]
Covered in discussion in #99 and #53
