### ISSUE TITLE
Suggestion for WebExt only approach

### ISSUE THREAD

**Issue by jobisoft** [TB-throwback/LookOut-fix-version#99]
I was thinking on how to make this add-on independent from legacy code, so we do not have to update it on each new release (TB intents to switch to monthly releases!)

We have no API jet to replace attachments in a viewed message. We could put effort into adding that. However we could also update the actual message and replace the attachment and reopen the modified message (for imap, this would fix the attachments on all connected devices). This is doable already. Alternatively we could not update the message, but create  a temporary message on the fly and open that.

**Comment by dugite-code** [comment]
> We have no API jet to replace attachments in a viewed message. We could put effort into adding that

I feel this would be the ideal option as modifying or creating emails isn't really something I would expect a client to do when just opening an email to view the contents.

In my opinion creating a temporary message is the best alternative method. Personally I feel it's not a good workflow to need to open an email in one client in order to view it in another client. Viewing email formats should be client side and any potential destructive email modifications should be a server side concern on message receipt.

We don't necessarily handle all the TNEF edge cases given it's a proprietary format, so any data loss from decoding errors is one of the key concerns for this plugin.

**Comment by jobisoft** [comment]
We could close this, as the Experiment used in the WebExtension rewrite (#102) looks like a good candidate to be added during this cycle and make Lookout a pure WebExtension.
